#lang racket/base
(define (grid edge)
  (build-list edge (lambda (x) (make-string edge #\0))))
(define (index i lst)
  (if (= i 0)
    (car lst)
    (index (sub1 i) (cdr lst))))
(define (direction-helper weights direction)
  (if (< direction 3)
    (if (<= (random) (car weights))
      direction
      (direction-helper (cdr weights) (add1 direction)))
    3))
(define (alter-grid grid-path pos val)
  (for/list ((i (build-list (string-length (car grid-path)) values))
             (line grid-path))
    (if (equal? i (cdr pos))
      (string-append (substring line 0 (car pos)) val (substring line (add1 (car pos))))
      line)))
(define (universal-weights values)
  (build-list 16 (lambda (x) values)))
(define default-weights (universal-weights (list 1/4 1/3 1/2)))
(define (snake edge weights)
  (let ((center (floor (/ edge 2))))
    (snake-helper (cons center center) edge (grid edge) weights 0)))
(define (snake-helper  pos edge grid-path weights i)
  (if (< i 1000000)
    (let ((seeker (lambda (x? +? x y)
                    (if (and (or x? +? (> (cdr pos) 0)) (or x? (not +?) (< (cdr pos) (sub1 edge))) (or (not x?) (not +?) (< (car pos) (sub1 edge))) (or (not x?) +? (> (car pos) 0)))
                      (string->number (substring (list-ref grid-path (+ (cdr pos) y)) (+ (car pos) x) (+ (car pos) x 1)))
                      1))))
      (let ((up (seeker #f #f 0 -1))
            (down (seeker #f #t 0 1))
            (right (seeker #t #t 1 0))
            (left (seeker #t #f -1 0)))
        (let* ((movement (index (+ (* 8 up) (* 4 down) (* 2 right) left) weights))
               (direction (direction-helper movement 0))
               (pos1 (lambda (delta-x delta-y) (cons (+ (car pos) delta-x) (+ (cdr pos) delta-y))))
               (next (lambda (move pos2)
                       (if (equal? move 0)
                         (snake-helper pos2 edge (alter-grid grid-path pos "1") weights (add1 i))
                         ;(snake-helper pos edge grid-path weights i)
                         ;(snake-helper pos edge grid-path weights (add1 i))
                         (list i pos (alter-grid grid-path pos "X"))
                         ))))
          (cond ((equal? direction 0) (next up (pos1 0 -1)))
                ((equal? direction 1) (next down (pos1 0 1)))
                ((equal? direction 2) (next right (pos1 1 0)))
                ((equal? direction 3) (next left (pos1 -1 0)))))))
    ;(cons increment weights)))
    (list i pos (alter-grid grid-path pos "X"))))
(snake 16 default-weights)